u<-vector()
w<-vector()
y<-vector()
x<-vector()
main<-function(m)
{
	set.seed(104729)
	u=runif(m)
	y=sqrt(u)
	x=exp(sqrt(u))
	c=(-1)*(cov(x,y)/var(y))
	w=x+c*(y-mean(y))
	thta=mean(w)
	quant=qnorm(0.975)
	lowerci=thta-(sqrt(var(w))*quant)/(sqrt(m))
	upperci=thta+(sqrt(var(w))*quant)/(sqrt(m))
	cat("The lower confidence interval for" ,m ," is : ",lowerci,"\n")
	cat("The higher confidence interval for" ,m ," is : ",upperci,"\n")
	vredtn=100*(var(w)-var(x))/var(x)
	cat("The percentage reduction for ",m,"is found to be ",vredtn,"\n")
}
main(100)
main(1000)
main(10000)
main(100000)